services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 18080:80
            - 10443:443
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=sqlite
            - APP_KEY=${APP_KEY}
            - APP_TIMEZONE=Europe/Berlin
            - DISPLAY_TIMEZONE=Europe/Berlin
            - CHART_DATETIME_FORMAT=d.m. H:i
            - DATETIME_FORMAT=d.m.Y, H:i:s
            - SPEEDTEST_SCHEDULE=5 */4 * * *
            - SPEEDTEST_SERVERS=53495,64700,20507,30907
        volumes:
            - /path/to/data:/config
            - /path/to-custom-ssl-keys:/config/keys
